---
privateIp: "192.168.33.12"
publicIp: "192.168.1.12"
cpus: 2
memory: 1555


themes:
 - name: themeName
   path: Development/themes/

modules:
 - name: moduleName
   path: Development/modules/

apps:
 - name: appName
   path: Development/apps/

