---
privateIp: "192.168.33.12"
publicIp: "192.168.1.12"
cpus: 1
memory: 512


box:
 name: ubuntu64
 version: 14_04


sentora: 
 tag: 1.0.0-RC2
 subDomain: panel.sitename.com
 path: Core/sentora-core/


themes:
 - name: themeName
   path: Development/themes/

modules:
 - name: moduleName
   path: Development/modules/

apps:
 - name: appName
   path: Development/apps/

